### ISSUE TITLE
The new Web-Service is very unreliable

### ISSUE THREAD

**Issue by novak-services** [MicroPyramid/forex-python#103]
Hi,

I am working in a project which uses forex-python regularly. But lately the webservice changed. We updated to 1.6. Since than, we got many troubles.

At first we got the error 

    RatesNotAvailableError("Currency Rates Source Not Ready")

So I incoporated the change, that was in one commit after the 1.6 release to prevent this error.

But after that, I still got some errors like that:

     RatesNotAvailableError("Currency Rate {0} => {1} not available for Date {2}")

We always access past rates with a date.

I was curious, what the reason was, so I tried to access the API myself. I got some very strange results. Everything seems to be Ok, with latest rates and also at business days. But when I try a non-Business date, it really gets strange.

Here some examples, I got:

4.4.:

     curl "https://theforexapi.com/api/2021-04-04/?base=GBP&symbols=EUR&rtype=fpy"

     Result: {"date":"2021-09-09","base":"EUR","rates":{}}

Particularly be aware here, that the base should be GBP, but is not!

5.4.:

     curl "https://theforexapi.com/api/2021-04-05/?base=GBP&symbols=EUR&rtype=fpy"
     
     Result: {"rates":{"USD":"1.1746"},"date":"2021-04-01","base":"EUR"}

Why do we get here USD? I tried the same call again, and was totally astonished.

5.4 Second Try:

     curl "https://theforexapi.com/api/2021-04-05/?base=GBP&symbols=EUR&rtype=fpy"

     Result: {"rates":{"GBP":"0.85195"},"date":"2021-04-01","base":"EUR"}

So the results are not even stable and I am not sure, if errors due to this unstable results can not lead to wrong rate results, since rates are exchanged and also dates can be wrong (and even more?).

I even tried to use the API without base and symbols, but even than I got wrong results eventually.

So in my opinion this web service is not usable at all in this state. Even when it would not be unstable, on non-working days, this service can not provide results. Working around this would be very cumbersome. But with the instability, even a workaround would be error-prone.

My question here: **Why do you use particularly this service and would it be feasible to use a different one?**

**Comment by BerendMosch** [comment]
Has there been any progress on this? The exact same issues still persist.

**Comment by qmhedging** [comment]
same "Currency Rates Source Not Ready"

for version 1.8

**Comment by ashwin31** [comment]
@qmhedging @BerendMosch @novak-services it is stable now. please check.

**Comment by ashwin31** [comment]
I will implement if you find any better service to be used.

**Comment by ekdevelop** [comment]
Is the website down again? Because i am getting the currencyRatesNot available error on 1.8
