### ISSUE TITLE
does not work with python 3.8

### ISSUE THREAD

**Issue by DidierDrogbaa** [MicroPyramid/forex-python#104]
Hello,
I want to ask if this module works with cryptocurrencies like OCEAN, DAI, Polkadot, etc.
Thanks

**Comment by coolfire1231** [comment]
Hi @DidierDrogbaa and @tocmgeborek,

yeah it will work on python 3.8

**Comment by ashwin31** [comment]
@DidierDrogbaa it won't work with those crypto currencies. share new feature request with the API details, we will see to implement.
