### ISSUE TITLE
RatesNotAvailableError when getting 'RUB' to 'USD' rate

### ISSUE THREAD

**Issue by bburbidge** [MicroPyramid/forex-python#113]
When running get_rate for 'RUB' to 'USD' for any date after 2022-3-1, a RatesNotAvailableError is returned.

**Comment by barashe** [comment]
> When running get_rate for 'RUB' to 'USD' for any date after 2022-3-1, a RatesNotAvailableError is returned.

I get the same error for every date I try. Up until now this happened randomly, but now it's consistent and I can't pull rates. 

python version: 3.9.4
forex_python version: 1.6

**Comment by ppeck** [comment]
I'm having the same issue getting the RatesNotAvailableError regardless of currency or date selected. Started having issues yesterday and am still unable to pull any rates. Running Python 3.8 and forex_python version 1.8

**Comment by vsia7** [comment]
I also get RatesNotAvailableError regardless of currency selected.

**Comment by ashwin31** [comment]
working now.
