### ISSUE TITLE
Forex SSL Certificate Expired

### ISSUE THREAD

**Issue by nathanf-p** [MicroPyramid/forex-python#123]
As per title, Postman is telling me the certificate has expired which resulted in some failed pulls this morning.

![image](https://user-images.githubusercontent.com/116276307/209157511-2d1a53a3-e602-4f4a-92e8-6f4b83f6ce0d.png)

Any chance this can be fixed?

**Comment by gringorichards** [comment]
I think its forex api site itself where the issue is, not the package bro

**Comment by nathanf-p** [comment]
Eh sorry, I must have had crossed wires. I thought that this package's owners run the API. Someone's already opened an issue on the API owner's page. But yeah thanks for the workaround! I'll close this now.
