### ISSUE TITLE
Able to use this with Anaconda/iPython?

### ISSUE THREAD

**Issue by yyiri** [MicroPyramid/forex-python#29]
Hi,

I tried conda install forex-python but am getting an error message:
"package missing in current win-64 channels"

Is it possible to use this with Anaconda please? Thanks a lot!

**Comment by hildogjr** [comment]
I nerd used, just passing here.
But in this case, you can install a package direct from GitHub

    pip install git+https://github.com/MicroPyramid/forex-python.git

**Comment by ravigadila** [comment]
make sure you have pip installed anaconda environment.
```
conda install pip
pip install forex-python
```
i think above will work.
