### ISSUE TITLE
Install under Python 3.6

### ISSUE THREAD

**Issue by bbruun** [MicroPyramid/forex-python#30]
On Arch 64bit using Python 3.6.2 I get the following error during pip (and manual installation after at git clone).

The problem is the README.rst file so there is a encoding issue in the file.

Emptying README.rst fixes the problem so `python setup.py install` works as intended.

```
Collecting forex-python
  Downloading forex-python-0.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-k7zj87sy/forex-python/setup.py", line 14, in <module>
        long_description="\n\n".join([open("README.rst").read()]),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3796: ordinal not in `range(128)

```

**Comment by benjaminbradley** [comment]
+1 same here
since installing via pip gives this error, the workaround is:

1. download [the source tarball](https://pypi.python.org/pypi/forex-python)
2. expand it
3. run `echo ''>README.rst`
4. then you can install normally with `python3 setup.py install`

**Comment by bbruun** [comment]
Thanks - I figured that our my self also even though I couldn't make out why the file was even used.
I'm up and running and it seems to be working fine. Thanks.
