### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by raztud** [MicroPyramid/forex-python#32]
pip install  forex-python
Collecting forex-python
  Using cached forex-python-0.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h1/nbbcsvp10jj11nqx1kf0j_6h0000gn/T/pip-build-jwkn3_qf/forex-python/setup.py", line 14, in <module>
        long_description="\n\n".join([open("README.rst").read()]),
      File "/Users/razvan/dev/venv/bin/../lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3796: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/h1/nbbcsvp10jj11nqx1kf0j_6h0000gn/T/pip-build-jwkn3_qf/forex-python/

```
(venv) $ pip --version
pip 9.0.1 from /Users/razvan/dev/venv/lib/python3.5/site-packages (python 3.5)
$ python --version
Python 3.5.2

$  uname -a
Darwin 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64

```

**Comment by ravigadila** [comment]
Issue is fixed in latest version of package.

https://pypi.python.org/pypi/forex-python/0.3.3
