### ISSUE TITLE
Translation into spanish

### ISSUE THREAD

**Issue by sleweddock** [MicroPyramid/forex-python#33]
I'd like to translate this repo into spanish , it will help a lot of users that don't know english plus it also brings more people into the forex world , please do let me know if there's a procedure I've to follow

**Comment by ravigadila** [comment]
@sleweddock  thanks for your interest in contribution and translating readme to other language.

create new file with `README_es.rst` for spanish language.
give file link in main README.rst
We will review your Pull request and merge if everything looks good.

**Comment by ravigadila** [comment]
closing as no response from @sleweddock
