### ISSUE TITLE
Deprecated Fixer.io API

### ISSUE THREAD

**Issue by Lucidiot** [MicroPyramid/forex-python#34]
The Fixer.io API currently in use by forex-python is deprecated and will stop working on June 1st. The new API requires a key, free keys only allow 1000 requests/month and EUR as the only base currency.

See the announcement on their GitHub repo: https://github.com/fixerAPI/fixer#readme

**Comment by ravigadila** [comment]
Changed currency source to https://ratesapi.io/api/ in new forex-python version(1.0.0) 

https://pypi.org/project/forex-python/
