### ISSUE TITLE
forex_python.converter.RatesNotAvailableError: Currency Rates Source Not Ready

### ISSUE THREAD

**Issue by ruoyush** [MicroPyramid/forex-python#40]
>>> from forex_python.converter import CurrencyRates
>>> c = CurrencyRates()
>>> c.get_rates('USD')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leo/miniconda3/envs/py3/lib/python3.6/site-packages/forex_python/converter.py", line 56, in get_rates
    raise RatesNotAvailableError("Currency Rates Source Not Ready")

Hi, I found this problem occurred tonight. Is there any problem with the new api source?

Thank you.

**Comment by GeneralTrader3** [comment]
I'm getting this too, I've been getting it periodically since the API change.

**Comment by ravigadila** [comment]
@GeneralTrader3 @ruoyush  API was down. 
Now everything will be okay. :)

**Comment by ruoyush** [comment]
Thank you~
