### ISSUE TITLE
Currency Rates Source Not Ready

### ISSUE THREAD

**Issue by upaang** [MicroPyramid/forex-python#41]
I am getting an exception: "forex_python.converter.RatesNotAvailableError: Currency Rates Source Not Ready". I checked the code, and basically, we are getting 404 while hitting [http://api.fixer.io/latest](http://api.fixer.io/latest).

Because of this, a non 200 code is generated and exception is getting raised.

**Comment by ravigadila** [comment]
@upaang please install forex-python==1.0.0.
fixer.io is deprecated.
we moved our api to https://ratesapi.io/api/latest in new forex-python.

**Comment by upaang** [comment]
Thanks a lot :)
