### ISSUE TITLE
RatesNotAvailableError

### ISSUE THREAD

**Issue by chatlourd** [MicroPyramid/forex-python#42]
raise RatesNotAvailableError("Currency Rates Source Not Ready")
forex_python.converter.RatesNotAvailableError: Currency Rates Source Not Ready

Anyone can help?

Looks like https://ratesapi.io/api/ is down

**Comment by tribikram-adhikari** [comment]
I have got the same error twice. Apparently, I have to run this module over a huge dataset and because of this error, this module is useless.

**Comment by ashwin31** [comment]
@chatlourd @tribikram-adhikari @collincburton 
we got very high traffic that we didn't prepared for. We have scaled up our server to meet the requirement.
Now, we are adding more caching , auto scaling and load balancer to make it available all the time. 
It will never go down again.
