### ISSUE TITLE
Currency Rates Source Not Ready

### ISSUE THREAD

**Issue by Irrawaddy** [MicroPyramid/forex-python#43]
This error has been going on since 5 June 2018:

File \forex_python\converter.py , line 56, in get_rates
    raise RatesNotAvailableError("Currency Rates Source Not Ready")
forex_python.converter.RatesNotAvailableError: Currency Rates Source Not Read

**Comment by ravigadila** [comment]
@Irrawaddy  which version of forex-python u are using?
 Install latest forex-python==1.0.0 to avoid RatesNotAvailableError
