### ISSUE TITLE
forex_python down?

### ISSUE THREAD

**Issue by chatlourd** [MicroPyramid/forex-python#51]
Getting the following error. Is the service down?
`    raise RatesNotAvailableError("Currency Rates Source Not Ready")
forex_python.converter.RatesNotAvailableError: Currency Rates Source Not Ready`

**Comment by phDooY** [comment]
You need to update package, as stated in description:

> Note: Install latest forex-python==1.1 to avoid RatesNotAvailableError

**Comment by ravigadila** [comment]
@chatlourd 
It's working fine.
reopen new ticket if u get same error
