### ISSUE TITLE
Source not available

### ISSUE THREAD

**Issue by westz36** [MicroPyramid/forex-python#53]
File "/usr/local/lib/python3.6/dist-packages/forex_python/converter.py", line 73, in get_rate
    raise RatesNotAvailableError("Currency Rates Source Not Ready")
forex_python.converter.RatesNotAvailableError: Currency Rates Source Not Ready

Requirement already satisfied: forex-python in /usr/local/lib/python3.6/dist-packages (1.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from forex-python) (2.20.0)
Requirement already satisfied: simplejson in /usr/local/lib/python3.6/dist-packages (from forex-python) (3.16.0)

**Comment by mbzand** [comment]
I had the same problem. Apparently, you need to update the forex-python package.
Uninstall it and install it again. Now it's working for me

**Comment by ravigadila** [comment]
some times https://ratesapi.io/ is not ready to respond. then you will see above error `Currency Rates Source Not Ready`.

please try after few minutes it will work.
