### ISSUE TITLE
Allow installation without dbus

### ISSUE THREAD

**Issue by pnhofmann** [MicroPyramid/forex-python#56]
Noticed, that 1.2 added a CLI interface which uses dbus-python.

Unfortunately since dbus-python is a requirement, this means, that dbus-python will be installed besides forex-python even if notification support or the cli interface is not needed.

This is problematic, because dbus-python needs C-Extension and therefore C compiler and Python development headers installed. That's nothing you want to install e.g. on a server or in a docker environment for no reason. Or have as a requirement for a application, which uses your library as backend - for no other reason.

So my question: Is there any way or would it possible to add a way to install forex-python without dbus-python?

**Comment by ashwin31** [comment]
Hi @pnhofmann you have a valid point.

I will remove the client and release new version in two hours.

Thank you for bringing this up.

**Comment by ravigadila** [comment]
@pnhofmann 
https://pypi.org/project/forex-python/ `forex-python==1.3`
removed CLI for now.
Later we will check see alternatives for `installation without dbus`

**Comment by pnhofmann** [comment]
Wow, that was fast! Thanks!
