### ISSUE TITLE
Japanese Yen and Chinese Yuan have the same unicode for their symbols

### ISSUE THREAD

**Issue by maxzzze** [MicroPyramid/forex-python#59]
https://github.com/MicroPyramid/forex-python/blob/master/forex_python/raw_data/currencies.json#L70

https://github.com/MicroPyramid/forex-python/blob/master/forex_python/raw_data/currencies.json#L31

**Comment by cmorph1** [comment]
Hi @maxzzze, 
I'm not sure what your issue is? The symbols are the same yes, but is this causing a problem?

**Comment by maxzzze** [comment]
No problem, closing.
