### ISSUE TITLE
ratesapi.io is down!

### ISSUE THREAD

**Issue by masaruduy** [MicroPyramid/forex-python#60]
ratesapi.io seems to have changed to https://exchangeratesapi.io/

**Comment by masaruduy** [comment]
I guess we just have to change line 27 of converter.py to return https://exchangeratesapi.io/

**Comment by DDoane** [comment]
actually needed to edit to
return "return https://api.exchangeratesapi.io/api/"

**Comment by wpla** [comment]
https://exchangeratesapi.io/ seems to be a competitor. Unlikely that MicroPyramid will change the URL. ratesapi.io is up, but the API is still not working.

**Comment by masaruduy** [comment]
https://ratesapi.io/api/latest works ...

**Comment by wpla** [comment]
The URL still needs to be changed from "https://ratesapi.io/api" to "https://api.ratesapi.io/api".

**Comment by ravigadila** [comment]
Hi All 
please install forex-pytho==1.5
source endpoint updated from `https://ratesapi.io/api` to `https://api.ratesapi.io/api`

https://github.com/MicroPyramid/forex-python/pull/62

**Comment by masaruduy** [comment]
thanks!
