### ISSUE TITLE
Currency Rates Source Not Ready

### ISSUE THREAD

**Issue by mrx23dot** [MicroPyramid/forex-python#65]
Requirement already satisfied: forex-python in c:\python36\lib\site-packages (1.1)

  File "C:\Python36\lib\site-packages\forex_python\converter.py", line 73, in get_rate
    raise RatesNotAvailableError("Currency Rates Source Not Ready")
forex_python.converter.RatesNotAvailableError: Currency Rates Source Not Ready

**Comment by afnadim** [comment]
I am having the same problem.Is it something wrong with the api?

**Comment by AliMZaini** [comment]
You have to change source url to "https://api.exchangeratesapi.io/api/" in converter.py

**Comment by jeindustries** [comment]
None of the above solutions worked, same error response. Any other idea on how to fix this issue?

**Comment by bubublik** [comment]
> None of the above solutions worked, same error response. Any other idea on how to fix this issue?

try to make request from another IP address

**Comment by fabouru1985** [comment]
Same from here!! "Currency Rates Source Not Ready"

**Comment by ben-dent** [comment]
Was this issue ever resolved?

**Comment by AliMZaini** [comment]
It seems to be working for me. Can you share the specifics of your problem, or is it identical to the OP?

**Comment by ben-dent** [comment]
I found that the reason it wasn't working for me is that the currency wasn't supported by the API. Would there be a possibility of a separate error message for that?

**Comment by purvapr13** [comment]
Same issue is coming to me. 
{'Error': 'forex_python.converter.RatesNotAvailableError: Currency Rates Source Not Ready'}
Could you please suggest on how to resolve it?

**Comment by tholness** [comment]
Currently working on version 1.5

**Comment by isadoradeckerlucke** [comment]
Hi--did you ever figure this out? I'm having the same issue. I checked with c.get_rates('USD') to make sure the codes i was entering were still valid, and they were, but no matter what country codes I enter i get this error each time. I have version 1.5 installed

**Comment by purvapr13** [comment]
Hi,

No, this issue was not resolved for me as well.

Purva Porwal

**Comment by Jasminyas** [comment]
You made too many call to the API called by the forex lib. you need to implement retry mechanism with a time.sleep, optimize function so it doesn't make too many calls in a short amount of time and/or try with another IP I belive.

**Comment by almir-campos** [comment]
I'm running the latest version of forex-python (just forked it - 1.5) and I have the same problem with the 'LKR' currency code. However, I didn't get any error with the other currency codes I tested.

**Comment by almir-campos** [comment]
Bad News: I just checked the status of the RatesAPI server at https://stats.uptimerobot.com/p8KZgsZ6J.
The status is: Rates API - ALL SYSTEMS DOWN (the uppercase is on me).

![image](https://user-images.githubusercontent.com/15270624/103449930-fa50ba80-4c63-11eb-8476-c9944b345b97.png)

**Comment by almir-campos** [comment]
I just send messages to the support team. Let's see.

**Comment by ravigadila** [comment]
We changed api to theforexapi.com
It works now. Please try.

**Comment by ekdevelop** [comment]
I am getting the error on 1.8. Is the website down?

**Comment by MailysRbt** [comment]
> 

Same here, it's probably down again.
