### ISSUE TITLE
Colombian peso don't work

### ISSUE THREAD

**Issue by arubiales** [MicroPyramid/forex-python#67]
RatesNotAvailableError: Currency Rates Source Not Ready

**Comment by AlliedToasters** [comment]
Bump. Argentinian peso does not work. 

`
---------------------------------------------------------------------------
RatesNotAvailableError                    Traceback (most recent call last)
<ipython-input-27-b75b03dbe48d> in <module>
      7     return c.convert(input_currency, output_currency, quantity, dt.datetime.strptime(date, '%Y-%m-%d'))
      8 
----> 9 convert('ARS', 'USD', 100, '2010-01-01')

<ipython-input-27-b75b03dbe48d> in convert(input_currency, output_currency, quantity, date)
      5 
      6 def convert(input_currency='EUR', output_currency='USD', quantity=100, date='2020-01-01'):
----> 7     return c.convert(input_currency, output_currency, quantity, dt.datetime.strptime(date, '%Y-%m-%d'))
      8 
      9 convert('ARS', 'USD', 100, '2010-01-01')

~/miniconda3/envs/learn/lib/python3.6/site-packages/forex_python/converter.py in convert(self, base_cur, dest_cur, amount, date_obj)
     98             except TypeError:
     99                 raise DecimalFloatMismatchError("convert requires amount parameter is of type Decimal when force_decimal=True")
--> 100         raise RatesNotAvailableError("Currency Rates Source Not Ready")
    101 
    102 

RatesNotAvailableError: Currency Rates Source Not Ready
`

**Comment by gusbemacbe** [comment]
@arubiales y @AlliedToasters, según la documentación https://forex-python.readthedocs.io/en/latest/currencysource.html, las monedas argentina, colombiana y de otros países hispanohablantes, excepto el Brasil y el México, no están en la lista de monedas suportadas.
