### ISSUE TITLE
Request: information on which side of the currency should the currency symbol should be displayed

### ISSUE THREAD

**Issue by kunambi** [MicroPyramid/forex-python#72]
It would be very nice/helpful if it was possible to retrieve information whether the currency symbol should be displayed on the left or right side of the value of the currency, i.e.:
`S$123` (Singapore Dollar, left) or `123€` (Euro, right)

**Comment by ashwin31** [comment]
I welcome a pull request.

**Comment by kunambi** [comment]
According to https://en.wikipedia.org/wiki/Currency_symbol, it seems that it's not a convention per symbol but rather in which language you're reading:

> In formatting, the symbol can use various formattings: before, between or after the numeric amounts: €2.50, 2,50 € and 2$50, for example; this positioning is determined by national convention.
