### ISSUE TITLE
Currency conversion for USD to LKR not found

### ISSUE THREAD

**Issue by lakithasahan** [MicroPyramid/forex-python#80]
raise RatesNotAvailableError("Currency Rates Source Not Ready")
forex_python.converter.RatesNotAvailableError: Currency Rates Source Not Ready

**Comment by isadoradeckerlucke** [comment]
Hi--did you ever figure this out? I'm having the same issue. I checked with c.get_rates('USD') to make sure the codes i was entering were still valid, and they were, but no matter what country codes I enter i get this error each time. I have version 1.5 installed

**Comment by peterirani** [comment]
Hi @lakithasahan, it looks like the `source_url()` (https://api.exchangeratesapi.io/api/) used by the library does not support LKR in it, hence it throws a `RatesNotAvailableError`.

Following are the currencies supported by the API link:

```json
{
   "rates":{
      "CAD":1.5444,
      "HKD":9.4132,
      "ISK":157.0,
      "PHP":58.379,
      "DKK":7.439,
      "HUF":358.61,
      "CZK":26.08,
      "AUD":1.5709,
      "RON":4.8748,
      "SEK":10.0715,
      "IDR":17126.85,
      "INR":88.5555,
      "BRL":6.5816,
      "RUB":91.2538,
      "HRK":7.563,
      "JPY":125.93,
      "THB":36.405,
      "CHF":1.0789,
      "SGD":1.6099,
      "PLN":4.5465,
      "BGN":1.9558,
      "TRY":8.9269,
      "CNY":7.8537,
      "NOK":10.3873,
      "NZD":1.6793,
      "ZAR":18.4065,
      "USD":1.2143,
      "MXN":24.3386,
      "ILS":3.9692,
      "GBP":0.88698,
      "KRW":1339.51,
      "MYR":4.9161
   },
   "base":"EUR",
   "date":"2021-01-26"
}
```

**Comment by ashwin31** [comment]
this is depending on a free service. We will add optional paid api support soon. someone raise a merge request and it will get merged eventually.
