### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by vnmabus** [MicroPyramid/forex-python#90]
First, thanks to the contributors of this project for their work, which they have offered without asking for anything in return.

It seems that this project has not received updates in two years. Moreover, the API that it uses has been changed and I am not sure that the PRs fixing that are going to be reviewed and merged. @ashwin31, as the original developer, can you tell us is there are plans to continue the maintenance of this project? If the answer is negative, maybe someone would want to step up to maintain it (or a fork), or we can switch dependencies to another project if this is going to be abandoned.

Thanks for your time!

**Comment by ashwin31** [comment]
updated few things and it's working now
