### ISSUE TITLE
EUR Currency is broken

### ISSUE THREAD

**Issue by MxBDriver** [MicroPyramid/forex-python#92]
EUR currency does not work properly. Convert from EUR to any other currency brings incorrect values at >1.
And converting from EUR to BTC <=1 also brings incorrect values.

**Comment by ravigadila** [comment]
@MxBDriver It works for me can you try again?

```
Python 3.8.10
>>> c.get_rate('EUR', 'INR')
'88.5590'

>>> from forex_python.bitcoin import BtcConverter
>>> b = BtcConverter()
>>> b.get_latest_price('USD')
33737.0517
>>> b.get_latest_price('EUR')
28434.4643

```
Feel free to reopen issue.
